### ISSUE TITLE
Handle request's content

### ISSUE THREAD

**Issue by sicardnicolas** [vadept/vachettp#10]
Handle the content of a request (POST, PUT, etc...)

**Comment by ghost** [comment]
you mean the body ?

**Comment by ghost** [comment]
I think we should manage binary content only, in order to avoid changing client / lib consumer format

**Comment by sicardnicolas** [comment]
yes, only plain, bare content, the rest is up to the user of the lib (or to another dependency, such as JsonRequest and JsonResponse for example).

**Comment by sicardnicolas** [comment]
Maybe we can close this one?
